### ISSUE TITLE
7/19 + 7/21 meetings: anyone wants to speak?

### ISSUE THREAD

**Issue by d-h-lee** [AIL-K/bamboo-forest#10]
See meeting schedule [link](https://github.com/AIL-K/bamboo-forest/blob/master/meetings.md).

I plan to take one session from each meeting. That leaves two open. 

- Monday: open to the entire lab. Any topic is fine.
- Wednesday: themed meeting. This week is "docker"

Contact me (@d-h-lee) if interested.

**Comment by d-h-lee** [comment]
@dkimds volunteered to give a gRPC overview talk in 7/19 meeting. This is about issue https://github.com/AIL-K/stylebot_dockers/issues/6

@dkimds Please take a slot you want on 7/19 in the markdown file (https://github.com/AIL-K/bamboo-forest/blob/master/meetings.md)

**Comment by cth127** [comment]
수요일 미팅도 정기적으로 진행이 되나요? 시간은 어떻게 되는지요?

**Comment by d-h-lee** [comment]
네네 정기적으로 진행하려 하고, 일단 수요일 오후시간을 생각하고 있어요. 저번에 1-3:30에 여름학기 이슈가 있다던거같아서 4-5 안이 가장 유력합니다.

**Comment by invigorator96** [comment]
@d-h-lee 1-3:30 에 있던 여름학기 이슈가 이제 사라졌습니다 ㅎㅎ;;;

**Comment by dkimds** [comment]
Here are the source code and the tutorial.
[grpc github](https://github.com/grpc/grpc)
[core concepts](https://grpc.io/docs/languages/python/quickstart/)
