### ISSUE TITLE
MDP primer

### ISSUE THREAD

**Issue by d-h-lee** [AIL-K/bamboo-forest#2]
You may need some intro to MDP and RL. Can we gather some resources available online?

**Comment by invigorator96** [comment]
Kaggle에 course 메뉴에서 다양한 내용을 커버하는 것 같아 이걸 따라서 공부해 보려고 스터디 방향 잡고 있었습니다. 여기에 mdp와 rl도 있을 것 같아요

**Comment by cth127** [comment]
https://hunkim.github.io/ml/ 저는 이번주 종강하면 담주부터 한번 따라가 보려구요! 딥러닝 공부할 때 썼었는데 RL 컨텐츠도 있네요!

**Comment by d-h-lee** [comment]
@cth127 훑어봤는데 상당히 꼼꼼하게 구성되어있군요. 수업 한 학기 정도 분량인듯합니다. 

@invigorator96 캐글 코스는 https://www.kaggle.com/learn/overview 이거 이야기하는거지요? 알려준대로, 종목별로 나눠져있는데 마지막에 Game이랑 RL이 있군요.

**Comment by cth127** [comment]
교수님 혹시 few shot learning 쪽도 관심 있으신가요? 전에 면담 때 메타러닝 말씀을 하셨던 기억이 나는데... openAI에서 저번달에 GPT-3라는 NLP transfer learning 모델을 냈는데, 아직 코드 공개는 되지 않았지만 퓨샷러닝을 강력하게 지원한대서요. 그래서 찾아봤는데 꽤 재밌는 아이디어인 거 같아서 파볼까 고민하고 있습니다.

**Comment by d-h-lee** [comment]
@cth127 Few shot learning 매우 재미난 주제이고, 파도파도 계속 나올 노다지광산 맞습니다. 그리고 말한대로 transfer learning의 관점을 통해서 접근하는 것이 빅데이터적인 정공법입니다. 흥미가 생기면 전진하세요.
