### ISSUE TITLE
Free lunch advisory today

### ISSUE THREAD

**Issue by d-h-lee** [AIL-K/bamboo-forest#3]
Today's deep RL seminar has free lunch.

Confirmed: Papa John's pizza
Possible additions: KFC

@cth127 @astrayne @gjwnsdud5076 @liquoricej @invigorator96 @prism4304 @comwitch

**Comment by d-h-lee** [comment]
Forecast: Pizza arrives at 12:20

**Comment by comwitch** [comment]
오늘 세미나를 소식을 아에 못들어서 참석못했는데,,, ㅠㅠ
