### ISSUE TITLE
No physical debriefing today (7/23) after deep learning seminar

### ISSUE THREAD

**Issue by d-h-lee** [AIL-K/bamboo-forest#4]
I am off to POSTECH tomorrow. So our debriefing today will be online at the 지역방송채널 document.

BTW, if anyone has suggestions/places to visit/things to do while I'm at POSTECH, feel free to comment as well.

**Comment by comwitch** [comment]
오늘 debriefing 지역방송채널 document에서 한다고 하셨는데 혹시 파일위치가 어디있는지 알 수 있습니까.

**Comment by d-h-lee** [comment]
@comwitch  https://docs.google.com/document/d/1NlTqQE3a3wcEgpel9MC9XzXz36fT725zYzLQE7pCyww/edit  입니다

**Comment by comwitch** [comment]
감사합니다!
