### ISSUE TITLE
Pizza at the deep learning seminar from 12:30PM today

### ISSUE THREAD

**Issue by d-h-lee** [AIL-K/bamboo-forest#5]
BTW are you not in the Kakaotalk chat room where this is announced? Let me know if you want to join there.

@astrayne @comwitch @cth127 @dkimds @gjwnsdud5076 @invigorator96 @liquoricej @prism4304

**Comment by comwitch** [comment]
혹시 초대가 안되어서 그러는데 초대해주시면 감사하겠습니다.

**Comment by astrayne** [comment]
저도 초대가 안되어있네요 초대해주시면 감사하겠습니다!

**Comment by d-h-lee** [comment]
> 
> 
> 저도 초대가 안되어있네요 초대해주시면 감사하겠습니다! (카톡 아이디 ispeaceful 입니다.)

Done
