### ISSUE TITLE
New private dataset available

### ISSUE THREAD

**Issue by d-h-lee** [AIL-K/bamboo-forest#8]
We have access to a new dataset (private). It is aimed to be turned into a paper as early as 2021 spring.

A brief explanation on the dataset can be found [here](
https://github.com/AIL-K/bamboo-forest#new-private-dataset-812 ).

If interested, comment below.

@astrayne @comwitch @cth127 @dkimds @gjwnsdud5076 @invigorator96 @liquoricej @prism4304

**Comment by cth127** [comment]
몇 가지 궁금한 점이 있는데 혹시 데이터를 어디서 받아볼 수 있을까요!

**Comment by invigorator96** [comment]
흥미 있습니다! 다만 데이터셋이 어떤 feature를 가지고 있고 그걸로부터 어떤 결과를 만들고자 하는지 혹시 얘기를 들을 수 있을까요..?

**Comment by gjwnsdud5076** [comment]
저도 참여하고 싶습니다

**Comment by d-h-lee** [comment]
@cth127 @invigorator96 @gjwnsdud5076 invitations are sent

**Comment by liquoricej** [comment]
저도 관심이 있습니다

**Comment by d-h-lee** [comment]
@liquoricej invited

**Comment by d-h-lee** [comment]
@prism4304  invited
