### ISSUE TITLE
12월3일 -- 송년의 이벤트 논의 겸 점심

### ISSUE THREAD

**Issue by d-h-lee** [AIL-K/bamboo-forest#9]
12월 3일이 수능날입니다. 수능 보러 가는 분들은 없겠지요? 

이날 아산이학관 615호에서 "점심식사 11:30 AM 출발" 예정입니다.

논의 주제는 "코로나 상황에도 안전하게 올 한해 다들 힘써주었음을 축하하는 송년이벤트 어떻게 할 수 있을까" 입니다.

참가의향과 추가하고 싶은 주제를 코멘트로 달아주세요!

@astrayne @comwitch @cth127 @dkimds @gjwnsdud5076 @invigorator96 @liquoricej @prism4304

**Comment by invigorator96** [comment]
참가 가능합니다! 다만 은행 방문 일정이 하나 있어서 얘기가 길어지면 먼저 일어나야 할 듯 합니다

**Comment by liquoricej** [comment]
저도 참가 가능합니다 :D

**Comment by prism4304** [comment]
내일 11시 30분 615호 앞에서 뵙겠습니다.

**Comment by cth127** [comment]
전 그때 수업이 있어서 송년회 때 뵙겟습니다~

**Comment by gjwnsdud5076** [comment]
참여하겠습니다

**Comment by comwitch** [comment]
저도 내일은 그때 수업이 있어서 힘들 것 같습니다. 송년회때 뵙겠습니다!

**Comment by dkimds** [comment]
송년회에서 뵙겠습니다.

**Comment by gjwnsdud5076** [comment]
교수님
![KakaoTalk_20201203_162251058](https://user-images.githubusercontent.com/58466569/100977194-fa399e00-3583-11eb-9483-22153d50a99e.png)
슬랙 링크로는 더이상 참여가 안됩니다

**Comment by invigorator96** [comment]
https://join.slack.com/t/ail-k/shared_invite/zt-jou8uo2t-3H7dqOe_8MagYckJJRuIGA 새로 만들었습니다
